kind: ConfigMap
apiVersion: v1
metadata:
  name: xxx-multimap
data:
  name: "Marco"
  age: 33
  test.conf: |
    env = plex-test
    endpoint = 0.0.0.0:31001
    char = utf8
    vault = PLEX/test
    log-size = 512M
---
apiVersion: v1
kind: Pod
metadata:
  name: startup-pod
  labels:
    sample: configmaps
spec:
  restartPolicy: OnFailure
  containers:
    - name: startup-pod-ctr
      image: busybox
      command: [ "/bin/sh", "-c", "echo First name $(FIRSTNAME) age $(AGE)", "wait" ]
      env:
        - name: NAME
          valueFrom:
            configMapKeyRef:
              name: xxx-multimap
              key: name
        - name: AGE
          valueFrom:
            configMapKeyRef:
              name: xxx-multimap
              key: age