kind: ConfigMap
apiVersion: v1
metadata:
  name: xxx-multimap
data:
  name: "Marco"
  age: 33
  test.conf: |
    env = plex-test
    endpoint = 0.0.0.0:31001
    char = utf8
    vault = PLEX/test
    log-size = 512M
