apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-oss-pvc
  namespace: nexus-oss
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      memory: "8Gi"
      cpu: "4"
      limits:
        memory: "8Gi"
        cpu: "4"
      storage: 8Gi
  storageClassName: local-storage