apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql16-pvc
  namespace: postgresql16-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: local-storage