apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: postgresql-pvc
    namespace: postgresql-ns
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /opt/k8s-worker-node1/postgresql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-worker-node1