global:
  postgresql:
    auth:
      postgresPassword: "gladiator"
      username: "keycloak"
      password: "secretes"
    database: "keycloak"
  storageClass: "local-storage"
primary:
  persistence:
    enabled: true
    existingClaim: "postgresql-pvc"
    storageClass: "local-storage"
volumePermissions:
  enabled: true