global:
  postgresql:
    auth:
      postgresPassword: "gladiator"
      username: "antares"
      password: "antares"
  storageClass: "local-storage"
primary:
  persistence:
    enabled: true
    existingClaim: "postgresql16-pvc"
    storageClass: "local-storage"
volumePermissions:
  enabled: true