apiVersion: v1
kind: Pod
metadata:
  name: xxx-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
    - name: xxx-ctr
      image: repo/tag
      ports:
        - containerPort: 8080
      resources:
        limits:
          memory: 256Mi
          cpu: 0.5