apiVersion: v1
kind: Pod
metadata:
  name: stateful-pod
spec:
  terminationGracePeriodSeconds: 1
  containers:
    - image: repo/tag:version
      name: stateful-pod-ctr
      tty: true
      stdin: true
  subdomain: web-service
  hostname: stateful-pod
---
# Headless Service for StatefulSet Pod DNS names
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: web
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: web
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: flash
provisioner: docker.io/hostpath
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tkb-sts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  serviceName: "web-service"
  template:
    metadata:
      labels:
        app: web
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: ctr-web
          image: nginx:latest
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: webroot
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: webroot
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "flash"
        resources:
          requests:
            storage: 1Gi