apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistence-volume-8g
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/home/ubuntu/data"
