apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistence-volume-4g
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/home/ubuntu/data"
