apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistence-volume-5g
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/home/ubuntu/data"
