apiVersion: v1
kind: Pod
metadata:
  name: dind-pod
  namespace: dind-ns
  labels:
    app: dind
spec:
  containers:
  - name: docker
    image: docker:27.1.1-dind-alpine3.20
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    volumeMounts:
    - name: docker-graph-storage
      mountPath: /var/lib/docker
  volumes:
    - name: docker-graph-storage
      emptyDir: {}